### ISSUE TITLE
Lack of installation and development documentation

### ISSUE THREAD

**Issue by lovingfeel** [dromara/dataCompare#1]
Lack of installation and development documentation
缺少 安装、开发文档

**Comment by zhugezifang** [comment]
后续会完善文档这块的

**Comment by zhugezifang** [comment]
> Lack of installation and development documentation 缺少 安装、开发文档

已经完善了安装文档

**Comment by coder-zc** [comment]
在这个问题下请问作者，ruoyi怎么结合本项目使用，application.ym那里没明白怎么配置，似乎也没有针对MacOS系统的操作。

**Comment by zhugezifang** [comment]
> 在这个问题下请问作者，ruoyi怎么结合本项目使用，application.ym那里没明白怎么配置，似乎也没有针对MacOS系统的操作。

不需要哈，只需要安装文档修改application.yml 数据库配置即可，其他不需要改动
